defmodule RankEm.Scrapers.NCAAB.Normalize do
  @moduledoc """
  Normalize team and conference names to those used by KenPom.
  """

  @conference_map %{
    "big10" => "B10",
    "bigten" => "B10",
    "big12" => "B12",
    "bigtwelve" => "B12",
    "mountainwest" => "MWC",
    "pac-12" => "P12",
    "pac12" => "P12",
    "pactwelve" => "P12",
    "bigeast" => "BE",
    "aac" => "Amer",
    "socon" => "SC",
    "atlantic10" => "A10",
    "atlanticten" => "A10",
    "atlanticsun" => "ASun",
    "asun" => "ASun",
    "ivyleague" => "Ivy",
    "ivy" => "Ivy",
    "southland" => "Slnd",
    "c-usa" => "CUSA",
    "bigwest" => "BW",
    "bigsky" => "BSky",
    "sunbelt" => "SB",
    "patriot" => "Pat",
    "pat" => "Pat",
    "horizon" => "Horz",
    "summit" => "Sum",
    "summitleague" => "Sum",
    "bigsouth" => "BSth",
    "americaeast" => "AE"
  }
  def conference(conf) do
    normalized = conf |> String.replace(~r/\s/, "") |> String.downcase()
    Map.get(@conference_map, normalized, conf)
  end

  @team_map %{
    "ETSU" => "East Tennessee St.",
    "Saint Mary's (CA)" => "Saint Mary's",
    "SFA" => "Stephen F. Austin",
    "Northern Colo." => "Northern Colorado",
    "Saint Francis (PA)" => "St. Francis PA",
    "Prairie View" => "Prairie View A&M",
    "LMU (CA)" => "Loyola Marymount",
    "N.C. Central" => "North Carolina Central",
    "Mississippi Val." => "Mississippi Valley St.",
    "Central Conn. St." => "Central Connecticut",
    "Southeastern La." => "Southeastern Louisiana",
    "North Carolina St." => "N.C. State",
    "NC State" => "N.C. State",
    "Fort Wayne" => "Purdue Fort Wayne",
    "LIU Brooklyn" => "LIU",
    "College of Charleston" => "Charleston",
    "Col. of Charleston" => "Charleston",
    "Louisiana Lafayette" => "Louisiana",
    "Gardner-Webb" => "Gardner Webb",
    "UTRGV" => "UT Rio Grande Valley",
    "Kansas City" => "UMKC",
    "Boston U." => "Boston University",
    "FGCU" => "Florida Gulf Coast",
    "Loyola Maryland" => "Loyola MD",
    "Grambling" => "Grambling St.",
    "Omaha" => "Nebraska Omaha",
    "Lamar University" => "Lamar",
    "Eastern Ky." => "Eastern Kentucky",
    "UIW" => "Incarnate Word",
    "Western Ky." => "Western Kentucky",
    "South Fla." => "South Florida",
    "UIC" => "Illinois Chicago",
    "Charleston So." => "Charleston Southern",
    "California Baptist" => "Cal Baptist",
    "A&M-Corpus Christi" => "Texas A&M Corpus Chris",
    "Middle Tenn." => "Middle Tennessee",
    "Albany (NY)" => "Albany",
    "CSU Bakersfield" => "Cal St. Bakersfield",
    "Ole Miss" => "Mississippi",
    "UNI" => "Northern Iowa",
    "SIUE" => "SIU Edwardsville",
    "North Ala." => "North Alabama",
    "UConn" => "Connecticut",
    "Western Mich." => "Western Michigan",
    "UMES" => "Maryland Eastern Shore",
    "Southeast Mo. St." => "Southeast Missouri St.",
    "Northern Ill." => "Northern Illinois",
    "N.C. A&T" => "North Carolina A&T",
    "Fla. Atlantic" => "Florida Atlantic",
    "Northern Ariz." => "Northern Arizona",
    "Southern Ill." => "Southern Illinois",
    "Army West Point" => "Army",
    "UT Martin" => "Tennessee Martin",
    "Western Caro." => "Western Carolina",
    "Southern California" => "USC",
    "Central Ark." => "Central Arkansas",
    "Western Ill." => "Western Illinois",
    "Southern U." => "Southern Utah",
    "McNeese" => "McNeese St.",
    "St. John's (NY)" => "St. John's",
    "Northern Ky." => "Northern Kentucky",
    "UNCW" => "UNC Wilmington",
    "Southern Miss." => "Southern Miss",
    "La.-Monroe" => "Louisiana Monroe",
    "Detroit Mercy" => "Detroit",
    "Miami (FL)" => "Miami FL",
    "Miami (OH)" => "Miami OH",
    "Central Mich." => "Central Michigan",
    "Eastern Ill." => "Eastern Illinois",
    "Ga. Southern" => "Georgia Southern",
    "St. Francis Brooklyn" => "St. Francis NY",
    "Bethune-Cookman" => "Bethune Cookman",
    "Ark.-Pine Bluff" => "Arkansas Pine Bluff",
    "Seattle U" => "Seattle",
    "Eastern Wash." => "Eastern Washington",
    "Eastern Mich." => "Eastern Michigan",
    "Alcorn" => "Alcorn St.",
    "CSUN" => "Cal St. Northridge"
  }

  def team(team) do
    Map.get(@team_map, team, team)
  end
end
